sudo: false

language: node_js

matrix:
  include:
    - node_js: 4
    - node_js: 5
      env: COVERALLS=1

after_success:
  - if [ "x$COVERALLS" = "x1" ]; then npm i coveralls && npm run cover && cat ./coverage/lcov.info | coveralls; fi
